# Generated by Django 3.2 on 2021-04-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name='Дата добавления')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование товара')),
                ('modifed_at', models.DateTimeField(verbose_name='Дата изменения')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('vendor', models.TextField(verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Карточка товара',
                'verbose_name_plural': 'Карточки товаров',
            },
        ),
    ]
